resource "azurerm_storage_account" "main" {
  name                     = local.storage_account_name
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"

  # All access happens through SAS tokens generated by the API; no anonymous public access.
  allow_nested_items_to_be_public = false
  min_tls_version                 = "TLS1_2"

  blob_properties {
    cors_rule {
      allowed_methods    = ["GET", "OPTIONS"]
      allowed_headers    = ["*"]
      exposed_headers    = ["Content-Disposition", "Content-Length", "Content-Type"]
      max_age_in_seconds = 86400
      # Azure Storage does not allow mixing "*" with specific origins.
      # When cors_origins is ["*"] it already covers everything, so skip the concat.
      allowed_origins = contains(var.cors_origins, "*") ? ["*"] : concat(var.cors_origins, var.local_dev_cors_origins)
    }
  }

  tags = local.tags
}

resource "azurerm_storage_container" "photos" {
  name                  = "photos"
  storage_account_id    = azurerm_storage_account.main.id
  container_access_type = "private"
}
